import type {
  PlantType,
  StoneVariant,
  themeType,
  WoodVariant,
} from './dropdown-types';

interface MaterialVariant {
  type: 'Wooden' | 'Stone';
  variant: WoodVariant | StoneVariant;
}

export interface ThemeMapping {
  flooringType: MaterialVariant[];
  panelingType: MaterialVariant[];
  plantType: PlantType[];
}

export const themeMappings: Record<themeType, ThemeMapping> = {
  Modern: {
    flooringType: [
      { type: 'Wooden', variant: 'European Oak' },
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Hard Maple' },
      { type: 'Wooden', variant: 'Beech' },
      { type: 'Wooden', variant: 'White Ash' },
      { type: 'Stone', variant: 'Honed Basalt' },
    ],
    panelingType: [
      { type: 'Wooden', variant: 'European Oak' },
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Hard Maple' },
      { type: 'Wooden', variant: 'Beech' },
      { type: 'Wooden', variant: 'White Ash' },
      { type: 'Stone', variant: 'Honed Basalt' },
    ],
    plantType: [
      'Snake Plant',
      'ZZ Plant',
      'Rubber Plant',
      'Monstera',
      'Philodendron',
      'Chinese Evergreen',
      'Peace Lily',
      'Areca Palm',
      'Bamboo Palm',
      'Kentia Palm',
    ],
  },
  Victorian: {
    flooringType: [
      { type: 'Wooden', variant: 'American Walnut' },
      { type: 'Wooden', variant: 'Santos Mahogany' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Stone', variant: 'Carrara Marble' },
    ],
    panelingType: [
      { type: 'Wooden', variant: 'American Walnut' },
      { type: 'Wooden', variant: 'Santos Mahogany' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Stone', variant: 'Carrara Marble' },
    ],
    plantType: [
      'Parlor Palm',
      'Boston Fern',
      'Dracaena',
      'Peace Lily',
      'Areca Palm',
      'Bamboo Palm',
      'Kentia Palm',
    ],
  },
  Minimalist: {
    flooringType: [
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Hard Maple' },
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'European Oak' },
      { type: 'Stone', variant: 'Honed Basalt' },
    ],
    panelingType: [
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Hard Maple' },
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'European Oak' },
      { type: 'Stone', variant: 'Honed Basalt' },
    ],
    plantType: [
      'Snake Plant',
      'ZZ Plant',
      'Bamboo Palm',
      'Pothos',
      'Philodendron',
      'Areca Palm',
      'Kentia Palm',
    ],
  },
  Contemporary: {
    flooringType: [
      { type: 'Wooden', variant: 'European Oak' },
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Hard Maple' },
      { type: 'Wooden', variant: 'Beech' },
      { type: 'Wooden', variant: 'White Ash' },
      { type: 'Wooden', variant: 'Black Ash' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Wooden', variant: 'Wenge' },
      { type: 'Stone', variant: 'Honed Basalt' },
    ],
    panelingType: [
      { type: 'Wooden', variant: 'European Oak' },
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Hard Maple' },
      { type: 'Wooden', variant: 'Beech' },
      { type: 'Wooden', variant: 'White Ash' },
      { type: 'Wooden', variant: 'Black Ash' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Wooden', variant: 'Wenge' },
      { type: 'Stone', variant: 'Honed Basalt' },
    ],
    plantType: [
      'Monstera',
      'Rubber Plant',
      "Bird's Nest Fern",
      'Areca Palm',
      'Bamboo Palm',
      'Bamboo Palm',
      'Kentia Palm',
    ],
  },
  Transitional: {
    flooringType: [
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'Red Oak' },
      { type: 'Wooden', variant: 'American Walnut' },
      { type: 'Wooden', variant: 'Hickory' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Stone', variant: 'Carrara Marble' },
      { type: 'Stone', variant: 'Italian Silver Gray Marble' },
      { type: 'Stone', variant: 'Tundra Gray Marble' },
    ],
    panelingType: [
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'Red Oak' },
      { type: 'Wooden', variant: 'American Walnut' },
      { type: 'Wooden', variant: 'Hickory' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Stone', variant: 'Carrara Marble' },
      { type: 'Stone', variant: 'Italian Silver Gray Marble' },
      { type: 'Stone', variant: 'Tundra Gray Marble' },
    ],
    plantType: [
      'Monstera',
      'Snake Plant',
      'ZZ Plant',
      'Pothos',
      'Philodendron',
      'Peace Lily',
      'Fern',
      'Areca Palm',
      'Bamboo Palm',
      'Bamboo Palm',
      'Kentia Palm',
    ],
  },
  'Mid Century Modern': {
    flooringType: [
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Wooden', variant: 'American Walnut' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Stone', variant: 'Black Slate' },
    ],
    panelingType: [
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Wooden', variant: 'American Walnut' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Stone', variant: 'Black Slate' },
    ],
    plantType: [
      'Monstera',
      'Snake Plant',
      'Rubber Plant',
      'Ponytail Palm',
      'Areca Palm',
      'Bamboo Palm',
      'Bamboo Palm',
      'Kentia Palm',
    ],
  },
  Bohemian: {
    flooringType: [
      { type: 'Wooden', variant: 'Bamboo' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Pecan' },
      { type: 'Wooden', variant: 'Hickory' },
      { type: 'Stone', variant: 'Slate' },
    ],
    panelingType: [
      { type: 'Wooden', variant: 'Bamboo' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Pecan' },
      { type: 'Wooden', variant: 'Hickory' },
      { type: 'Stone', variant: 'Slate' },
    ],
    plantType: [
      'Monstera',
      'Pothos',
      'Philodendron',
      'Fern',
      'Spider Plant',
      'Peace Lily',
      'Rubber Plant',
      'Areca Palm',
      'Bamboo Palm',
      'Bamboo Palm',
      'Kentia Palm',
    ],
  },
  'Pakistani Traditional': {
    flooringType: [
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Bamboo' },
      { type: 'Wooden', variant: 'Acacia' },
      { type: 'Wooden', variant: 'American Walnut' },
      { type: 'Stone', variant: 'Carrara Marble' },
      { type: 'Stone', variant: 'Slate' },
    ],
    panelingType: [
      { type: 'Wooden', variant: 'Teak' },
      { type: 'Wooden', variant: 'Sapele' },
      { type: 'Wooden', variant: 'Bamboo' },
      { type: 'Wooden', variant: 'Acacia' },
      { type: 'Wooden', variant: 'American Walnut' },
      { type: 'Stone', variant: 'Carrara Marble' },
      { type: 'Stone', variant: 'Slate' },
    ],
    plantType: [
      'Monstera',
      'Rubber Plant',
      'Peace Lily',
      'Fern',
      'Spider Plant',
      'Areca Palm',
      'Bamboo Palm',
      'Bamboo Palm',
      'Kentia Palm',
    ],
  },
  Mediterranean: {
    flooringType: [
      { type: 'Stone', variant: 'Carrara Marble' },
      { type: 'Stone', variant: 'White Carrara Marble' },
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Hard Maple' },
      { type: 'Wooden', variant: 'Soft Maple' },
    ],
    panelingType: [
      { type: 'Stone', variant: 'Carrara Marble' },
      { type: 'Stone', variant: 'White Carrara Marble' },
      { type: 'Wooden', variant: 'White Oak' },
      { type: 'Wooden', variant: 'Birch' },
      { type: 'Wooden', variant: 'Hard Maple' },
      { type: 'Wooden', variant: 'Soft Maple' },
    ],
    plantType: [
      'Monstera',
      'Snake Plant',
      'Areca Palm',
      'Bamboo Palm',
      'Bamboo Palm',
      'Kentia Palm',
      'Majesty Palm',
      'Peace Lily',
    ],
  },
};
